### ISSUE TITLE
Fix kubeconfig permissions

### ISSUE THREAD

**Issue by vineethvijay7** [google-github-actions/get-gke-credentials#301]
### TL;DR

Right now the default kubeconfig file generated has permissions which makes this warning:

`WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/runner/work/<>/gha-kubeconfig-15623d46f9e36f37`

It could include the fixes mentioned over here : https://github.com/helm/helm/issues/9115

### Action YAML

```yaml
- name: Authenticate to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_TF_SA_CREDS }}'

      - name: Get GKE k8s creds
        id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GCP_TF_CLUSTER_NAME }}'
          location: '${{ env.GCP_TF_LOCATION }}'
          project_id: '${{ env.GCP_TF_PROJECT_ID }}'
```
